#!/bin/sh

## Had to disable this, otherwise script doesn't contunue after wget.
#set -e

export LANG=en_US.UTF-8

if [ -z "$1" ]; then
    echo "No config given."
    exit 1
fi

if [ ! -f "$1" ]; then
    echo "Config $1 not found."
    exit 1
fi

CONF="$(dirname "$1")/liquidsoap-queue.conf"

if [ ! -f "$CONF" ]; then
    echo "Config file '$CONF' not found."
    exit 1
fi

. "$CONF"

WAIT='wait'

if [ -n "$REMOTE" ]; then
    while [ _$WAIT = _'wait' ]; do
        wget -U 'Radio Arena AutoDJ Queue https://forum.theprodigy.ru/radio/' --spider -q -t 1 -T 3 "$SITEDIR.running"
        if [ $? -eq 0 ]; then
            echo "$(date)  Still waiting..."
            sleep 10m
        else
            WAIT='none'
        fi
    done
else
    while [ _$WAIT = _'wait' ]; do
        if [ -f "$DESTINATION.running" ]; then
            echo "$(date)  Still waiting..."
            sleep 10m
        else
            WAIT='none'
        fi
    done
fi

echo "$(date)  OK, started."

if [ -n "$REMOTE" ]; then
    rsync -avv --delete "$SOURCE" "$DESTINATION"
fi

DIR="$(dirname "$0")"
EXEC="$DIR/liquidsoap-queue.pyo"

## Use Python from virtualenv if exists.
LOCALPYTHON="$(dirname "$DIR")/virtualenv/bin/python"
if [ -f "$LOCALPYTHON" ]; then
    PYTHON="$LOCALPYTHON"
else
    PYTHON='python2.7'
fi

echo "Python is $PYTHON"

if [ ! -f "$EXEC" ]; then
    if [ -f "$DIR/liquidsoap-queue.py" ]; then
        "$PYTHON" -OO -m compileall "$DIR/liquidsoap-queue.py"
    else 
        echo "Executable $DIR/liquidsoap-queue.py not found."
        exit 1
    fi
fi

exec "$PYTHON" "$EXEC" "$@"
