#!/bin/sh

if [ -z "$1" ]; then
    echo "No config given."
    exit 1
fi

## Trying to avoid restricted filenames issue.
export LANG='en_US.UTF-8'

## Settign PATH. Sometimes crontab doesn't has /usr/local/bin path
## and ffmpeg may not be visible if it's installed from sources.
export PATH=/usr/local/bin:/usr/bin:/bin

DIR="$(dirname "$0")"

EXEC="$DIR/__init__.pyo"

## Use Python from virtualenv if exists.
LOCALPYTHON="$(dirname "$DIR")/virtualenv/bin/python"
if [ -f "$LOCALPYTHON" ]; then
    PYTHON="$LOCALPYTHON"
else
    PYTHON='python2.7'
fi

echo "Python is $PYTHON"

if [ ! -f "$EXEC" ]; then
    if [ -f "$DIR/__init__.py" ]; then
        "$PYTHON" -OO -m compileall "$DIR/__init__.py"
    else 
        echo "Executable $DIR/__init__.py not found."
        exit 1
    fi
fi

exec "$PYTHON" "$EXEC" "$@"
